eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: feign-service
#添加feign自动熔断处理
feign:
  hystrix:
    enabled: true